#pragma once
#ifdef DELTA_ZERO

#define DEFAULT_RD_F	160
#define DEFAULT_RD_E	40
#define DEFAULT_RD_RF	200	
#define DEFAULT_RD_RE	512 

#define DEFAULT_RD_W	0.0

#define DEFAULT_MOVING_AREA_X		250
#define DEFAULT_MOVING_AREA_Y		250
#define DEFAULT_MOVING_AREA_Z	    600

#define DEFAULT_MOVING_AREA_LARGEST_DIAMETER	500			

#define THETA1_HOME_POSITION -29.5				
#define THETA2_HOME_POSITION -31
#define THETA3_HOME_POSITION -27

#define THETA1_STEPS_PER_2PI 	9600				
#define THETA2_STEPS_PER_2PI  	9600
#define THETA3_STEPS_PER_2PI  	9600

#endif
