#ifndef INC_PIN_H_
#define INC_PIN_H_

#include "stm32f1xx_hal.h"

#define THETA1_PULSE_PIN GPIOB, GPIO_PIN_6
#define THETA2_PULSE_PIN GPIOB, GPIO_PIN_3
#define THETA3_PULSE_PIN GPIOA, GPIO_PIN_11

#define THETA1_DIRECTION_PIN GPIOB, GPIO_PIN_7
#define THETA2_DIRECTION_PIN GPIOB, GPIO_PIN_4
#define THETA3_DIRECTION_PIN GPIOA, GPIO_PIN_12

#define THETA1_ENDSTOP_PIN GPIOA, GPIO_PIN_7
#define THETA2_ENDSTOP_PIN GPIOA, GPIO_PIN_6
#define THETA3_ENDSTOP_PIN GPIOA, GPIO_PIN_5

#define VACCUM_PIN GPIOB, GPIO_PIN_12
#define DIR_LOADER_PIN GPIOB, GPIO_PIN_13
#define PUL_LOADER_PIN GPIOB, GPIO_PIN_15
#define ENABLE_ALL_PIN GPIOB,GPIO_PIN_14

#define SET GPIO_PIN_SET
#define RESET GPIO_PIN_RESET

void WRITE(GPIO_TypeDef *GP, uint16_t Pin, GPIO_PinState State);

bool READ(GPIO_TypeDef *GP, uint16_t Pin) ;

#endif

